-- ============================================================================
-- Cheers — Wikimedia photo enrichment for `public.pois`
-- ----------------------------------------------------------------------------
-- Apply after `20260705180000_enrich_pois.sql`.
--
-- Auto-generated by `scripts/enrich_poi_images.py`. Regenerate with:
--   python3 scripts/enrich_poi_images.py > <this file>
--
-- Matched: 51 / 72 POIs
-- Misses (21):
--   • Eurostars Grand Marina — no Wikimedia image found
--   • Hotel Gargallo Rialto — no Wikimedia image found
--   • Sercotel Rosellón — not yet fetched
--   • Arab Halal Marrakech — no Wikimedia image found
--   • Asado Bufet Lliure de Carns Argentines — no Wikimedia image found
--   • Ciutat Comtal — no Wikimedia image found
--   • El Argentino — no Wikimedia image found
--   • Micu Maku — no Wikimedia image found
--   • Mirablau — no Wikimedia image found
--   • Vivo Tapas — no Wikimedia image found
--   • 100 Montaditos — no Wikimedia image found
--   • Bar El Velódromo — no Wikimedia image found
--   • Bar Jai-Ca — no Wikimedia image found
--   • Bar Lobo — no Wikimedia image found
--   • Bodega Joan — no Wikimedia image found
--   • Can Paixano — no Wikimedia image found
--   • El Bosc de Les Fades — no Wikimedia image found
--   • Perikete — no Wikimedia image found
--   • Quimet & Quimet — no Wikimedia image found
--   • Sheoudo Condal — no Wikimedia image found
--   • Tapeo — no Wikimedia image found
-- ============================================================================

-- Barcelo Raval (wikidata P18: El Raval)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://commons.wikimedia.org/wiki/Special:FilePath/105_Museu_d%27Hist%C3%B2ria_de_Catalunya%2C_vista_a%C3%A8ria_del_Raval.JPG?width=800","width":800,"height":null,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '2ba6c1c1-098f-5a3a-af0b-3470820e7e20';

-- Casa Gràcia (en geosearch: Casa Bonaventura Ferrer)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/f/f4/Casa_Ferrer.jpg","width":796,"height":1250,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '1f8a3dec-5fda-5e0b-b434-648b1e91f2ae';

-- El Palace Hotel (ca geosearch: Hotel Palace (Barcelona))
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Hotel_Ritz_-_20240122_124605.jpg/960px-Hotel_Ritz_-_20240122_124605.jpg","width":800,"height":1067,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '5f6d41c1-fed5-5922-9235-1e94df03d1c6';

-- H10 Marina Barcelona Hotel (wikidata P18: H10 Marina Barcelona Hotel)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://commons.wikimedia.org/wiki/Special:FilePath/H10_Marina_Barcelona_Hotel.jpg?width=800","width":800,"height":null,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '502fe53c-9c91-5e17-8a90-400422761248';

-- Hotel Arts Barcelona (en geosearch: Hotel Arts)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Hotel_Arts_by_night.JPG/960px-Hotel_Arts_by_night.JPG","width":800,"height":1200,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '6d1dd55c-b637-5ed1-a862-d6499062eee2';

-- Hotel Barceló Sants (en geosearch: Barcelona Sants railway station)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Estacio_Barcelona_Sants_-_3_-_2010-10-18_-_JTCurses.jpg/960px-Estacio_Barcelona_Sants_-_3_-_2010-10-18_-_JTCurses.jpg","width":800,"height":531,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'ac011245-dd5a-5ce7-9c3c-e12c32592ae9';

-- Hotel Casa Fuster (en geosearch: Casa Bonaventura Ferrer)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/f/f4/Casa_Ferrer.jpg","width":796,"height":1250,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '2c8d4dac-05d7-5c57-b157-63f1799e25b9';

-- Hotel Catalonia Barcelona Plaza (wikidata P18: Arenas de Barcelona)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://commons.wikimedia.org/wiki/Special:FilePath/Arenas_de_Barcelona.jpg?width=800","width":800,"height":null,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'e00a064d-a60e-5290-b9d9-226244018d38';

-- Hotel Condes de Barcelona (en geosearch: Hotel Majestic (Barcelona))
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Hotel_Majestic_Barcelona.JPG/960px-Hotel_Majestic_Barcelona.JPG","width":800,"height":1067,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '83a5ff20-90fd-5749-bb92-7ca4dbb78f11';

-- Intercontinental Barcelona (en geosearch: Palau dels Esports de Barcelona)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Barcelona_Teatre_Musical_-_%28Catalonia%29.jpg/960px-Barcelona_Teatre_Musical_-_%28Catalonia%29.jpg","width":800,"height":496,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'b14c098c-06db-5113-b364-47ee87fcdb7b';

-- Majestic Hotel and Spa (en geosearch: Hotel Majestic (Barcelona))
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Hotel_Majestic_Barcelona.JPG/960px-Hotel_Majestic_Barcelona.JPG","width":800,"height":1067,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'b45199f8-d4dc-550b-b0cb-745bc1791c70';

-- Mandarin Oriental Barcelona (en geosearch: Mandarin Oriental, Barcelona)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Mandarin_Oriental_Barcelona.jpg/960px-Mandarin_Oriental_Barcelona.jpg","width":800,"height":1108,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '3daf12a0-55a1-5b1a-adec-21284cc3d806';

-- Meliá Barcelona Sky (en geosearch: Hotel Melia Barcelona Sky)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Barcelona_%28Poblenou%29._Melia_Barcelona_Sky_Hotel._1999-2008._Dominique_Perrault%2C_architect._%2825836731291%29.jpg/960px-Barcelona_%28Poblenou%29._Melia_Barcelona_Sky_Hotel._1999-2008._Dominique_Perrault%2C_architect._%2825836731291%29.jpg","width":800,"height":1204,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '8b5f34c0-fd3d-5565-89f8-25c2ee849049';

-- Novotel Barcelona City (wikidata P18: Novotel Barcelona City)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://commons.wikimedia.org/wiki/Special:FilePath/Novotel_Barcelona_City.jpg?width=800","width":800,"height":null,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '0cbe66cf-948f-54e3-8989-650381677db9';

-- W Barcelona (en geosearch: W Barcelona)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/14-08-05-barcelona-RalfR-001.jpg/960px-14-08-05-barcelona-RalfR-001.jpg","width":800,"height":531,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '24634b57-4f50-5359-a2c4-77a4872ea4f9';

-- 7 Portes (ca geosearch: Set Portes)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/007_Porxos_d%27en_Xifr%C3%A9%2C_7_Portes.JPG/960px-007_Porxos_d%27en_Xifr%C3%A9%2C_7_Portes.JPG","width":800,"height":600,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '752f9ef9-1d7c-52cb-abc6-8fbb1b68c298';

-- Antigua (en title: Antigua)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/7/7e/Antigua.JPG","width":539,"height":398,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '2b41fd08-2f06-56f3-8559-7fa34250b7bd';

-- Botafumeiro (en title: Botafumeiro)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Santiago_Compostela_Cathedral_2023_-_the_botafumeiro.jpg/960px-Santiago_Compostela_Cathedral_2023_-_the_botafumeiro.jpg","width":800,"height":1200,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '28f062e3-4290-5592-96fe-c31e1ba27531';

-- Cañete (en title: Cañete, Chile)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Clava_symbol_in_Ca%C3%B1ete%2C_Chile.JPG/960px-Clava_symbol_in_Ca%C3%B1ete%2C_Chile.JPG","width":800,"height":600,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'a80cbebb-942e-52ee-ba69-fb5bc88ba7fe';

-- Colom Restaurant (en title: Colony (restaurant))
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Colony%2C_Marylebone%2C_W1_%286042440949%29.jpg/960px-Colony%2C_Marylebone%2C_W1_%286042440949%29.jpg","width":800,"height":533,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '07a1be0a-8bb4-5fec-bbff-d483dae453db';

-- Jesús Restaurant (en title: Jeju (restaurant))
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/e/e9/Jeju_%28restaurant%29_logo.png","width":328,"height":240,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'c686ceea-b320-5f77-b0a5-b2c3e4b57a93';

-- La Fonda (en title: La Fonda on the Plaza)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/La_fonda_sw_view.jpg/960px-La_fonda_sw_view.jpg","width":800,"height":1200,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'bcbd68ca-8e98-5913-8e57-3f31119a725e';

-- Ocaña (en title: Ocaña, Spain)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/PanoramaDeOca%C3%B1a-rectangular.jpg/960px-PanoramaDeOca%C3%B1a-rectangular.jpg","width":800,"height":275,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '8a0cc312-2fe9-5d9a-b733-dfc92db89b22';

-- Restaurant La Boqueria (ca geosearch: Font del Pla de la Boqueria)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/025_Font_del_pla_de_la_Boqueria.jpg/960px-025_Font_del_pla_de_la_Boqueria.jpg","width":800,"height":1067,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'a754ffb7-0b16-56e4-bad0-707766802434';

-- Restaurante La Barca del Salamanca (wikidata P18: Edifici del carrer Salamanca, 42-44)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://commons.wikimedia.org/wiki/Special:FilePath/Edifici_del_carrer_Salamanca%2C_42-44.jpg?width=800","width":800,"height":null,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'dfa5d79b-6cca-5fcc-9279-248a42dec479';

-- Salamanca (en title: Salamanca)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/68436-Salamanca_%2849093713952%29_edited.jpg/960px-68436-Salamanca_%2849093713952%29_edited.jpg","width":800,"height":427,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '20bbfed9-3767-5ee8-9b8a-e681fbdc0ac2';

-- Bar del Pla (wikidata P18: Museu del Mamut)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://commons.wikimedia.org/wiki/Special:FilePath/Museo_del_Mamut.jpg?width=800","width":800,"height":null,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'c8ede737-edae-5deb-83d4-a5a212e66b36';

-- Cerveseria Vaso de Oro (ca geosearch: Estació de Barceloneta)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Barcelona_-_Metro_-_Estaci%C3%B3_de_Barceloneta_%287480533516%29.jpg/960px-Barcelona_-_Metro_-_Estaci%C3%B3_de_Barceloneta_%287480533516%29.jpg","width":800,"height":600,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'a5ceda1c-687b-5eca-b1c9-7cfaa8a70c02';

-- El Xampanyet (ca geosearch: El Xampanyet)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/055_El_Xampanyet%2C_c._Montcada_22_%28Barcelona%29.jpg/960px-055_El_Xampanyet%2C_c._Montcada_22_%28Barcelona%29.jpg","width":800,"height":600,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '48aff205-76b2-5a0c-bbaa-859d2476360b';

-- Fàbrica Moritz Barcelona (ca geosearch: Fàbrica de cervesa Moritz)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/3/3e/Cervezas_Ernesto_Petry.jpg","width":445,"height":320,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '3b003824-1a3c-51af-b1c5-f181e0811ac0';

-- La Bombeta (ca geosearch: Mercat de la Barceloneta)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Mercat_de_la_Barceloneta_-_panoramio.jpg/960px-Mercat_de_la_Barceloneta_-_panoramio.jpg","width":800,"height":404,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '87392bea-d4e2-56f8-b581-e02535a0433e';

-- Michael Collins (en title: Michael Collins (Irish leader))
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/0/0e/Michael_Collins.jpg","width":736,"height":994,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'c2b6ded1-3a51-5fea-8d19-caf3681fbd86';

-- Paradiso (en title: Paradiso)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Firenze%2C_commedia_di_dante%2C_paradiso%2C_1325-50_%28con_intregrazioni_dei_canti_VI-XXXIII_del_xix_sec%29%2C_pluteo_40.15%2C_c_5v%2C_01.JPG/960px-Firenze%2C_commedia_di_dante%2C_paradiso%2C_1325-50_%28con_intregrazioni_dei_canti_VI-XXXIII_del_xix_sec%29%2C_pluteo_40.15%2C_c_5v%2C_01.JPG","width":800,"height":600,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '42cb4d38-529f-55f9-ac9a-073c16a0668b';

-- Arc de Triomf (en geosearch: Arc de Triomf)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Barcelona_-_Arc_de_Triomf_%282%29.JPG/960px-Barcelona_-_Arc_de_Triomf_%282%29.JPG","width":800,"height":561,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '93db60cb-25df-5dca-8eef-c546a89f2ec5';

-- Barcelona Maritime Museum (en geosearch: Maritime Museum of Barcelona)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Drassanes_de_Barcelona.jpg/960px-Drassanes_de_Barcelona.jpg","width":800,"height":720,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'f2117be4-38e2-59b7-b380-c147a6350889';

-- Capella de Santa Agata (en geosearch: Chapel of Santa Àgata)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Capella_de_Santa_%C3%80gata.JPG/960px-Capella_de_Santa_%C3%80gata.JPG","width":800,"height":532,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '66c56bf9-56b7-59f8-be3e-a510528d7856';

-- Casa Batlló (en geosearch: Casa Batlló)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Casa_Batllo_Overview_Barcelona_Spain_cut.jpg/960px-Casa_Batllo_Overview_Barcelona_Spain_cut.jpg","width":800,"height":986,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'ae9f8364-5da0-53a3-b827-dc0f6ac811c0';

-- Casa Vicens Gaudí (en geosearch: Casa Vicens)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Gaud%C3%AD_-_Casa_Vicens.JPG/960px-Gaud%C3%AD_-_Casa_Vicens.JPG","width":800,"height":600,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '67f91705-8d09-53ad-b3aa-7d81464da775';

-- CosmoCaixa Museum of Science (ca geosearch (sightseeing): Empar de Santa Llúcia)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Barcelona._Cosmocaixa_Museum_%28originally_a_charity_house_for_blind_persons%29._1904-1909._Josep_Dom%C3%A8nech_i_Estap%C3%A0%2C_architect_%2833995548580%29.jpg/960px-Barcelona._Cosmocaixa_Museum_%28originally_a_charity_house_for_blind_persons%29._1904-1909._Josep_Dom%C3%A8nech_i_Estap%C3%A0%2C_architect_%2833995548580%29.jpg","width":800,"height":531,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '1cacd6cf-2d61-5aab-9a13-a55212437402';

-- Joan Miró Foundation (en geosearch: Fundació Joan Miró)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Joan_Mir%C3%B3_i_l%27Objecte_2016.jpg/960px-Joan_Mir%C3%B3_i_l%27Objecte_2016.jpg","width":800,"height":600,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '25b7d5b8-20c7-5195-81a3-05528b399353';

-- La Pedrera - Casa Milà (en geosearch: Casa Milà)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Casa_Mil%C3%A0%2C_general_view.jpg/960px-Casa_Mil%C3%A0%2C_general_view.jpg","width":800,"height":623,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '8cea3134-5bd8-5402-8670-dcaf64d82ffe';

-- Magic Fountain of Montjuïc (en geosearch: Magic Fountain of Montjuïc)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Barcelona_-_Font_M%C3%A0gica_-_2016.jpg/960px-Barcelona_-_Font_M%C3%A0gica_-_2016.jpg","width":800,"height":533,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'd5479945-6cb8-5cd7-ab88-334bead53bef';

-- Montjuïc Castle (en geosearch: Montjuïc Castle)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Castell_de_Montjuic_-_Fossat_entrada_-_Barcelona_%28Catalonia%29.jpg/960px-Castell_de_Montjuic_-_Fossat_entrada_-_Barcelona_%28Catalonia%29.jpg","width":800,"height":600,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '84991060-bbfd-5bde-b4e3-1167b07c4099';

-- Monument a Colom (en geosearch: Columbus Monument, Barcelona)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Photo_of_Colombus_Monument_taken_with_iPhone_13_Pro.jpg/960px-Photo_of_Colombus_Monument_taken_with_iPhone_13_Pro.jpg","width":800,"height":1312,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = 'df075847-30e7-52c0-99df-b19540fd7d69';

-- Palau Güell (en geosearch (sightseeing): Royal Square (Barcelona))
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/f/ff/Barcellona_Pla%C3%A7a_Reial.jpg","width":640,"height":480,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '02f96bbf-a345-527d-a5f9-616b3012ad59';

-- Parc del Mirador del Poble-sec (ca geosearch: Parc del Mirador del Poble-sec)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Mirador_Poble_Sec.JPG/960px-Mirador_Poble_Sec.JPG","width":800,"height":600,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '0a0fe1a7-7f10-533b-a98f-8c0145845750';

-- Park Güell (en geosearch: Park Güell)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Parc_guell_-_panoramio.jpg/960px-Parc_guell_-_panoramio.jpg","width":800,"height":600,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '1aac4ca1-9b7f-5509-a58c-09f95776ea53';

-- Plaça d'Espanya (en geosearch: Plaça d'Espanya station)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Fale_-_Barcellona_-_266.jpg/960px-Fale_-_Barcellona_-_266.jpg","width":800,"height":600,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '11c34e22-c882-579e-b0bb-462f6524f865';

-- Plaça de Catalunya (en geosearch: Plaça de Catalunya)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Catalunya_Barcelona1_tango7174.jpg/960px-Catalunya_Barcelona1_tango7174.jpg","width":800,"height":364,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '6d7f9975-84db-525b-afd6-aee165e25860';

-- Poble Espanyol (en geosearch: Poble Espanyol)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Poble_Espanyol_-_Torres_de_%C3%81vila.jpg/960px-Poble_Espanyol_-_Torres_de_%C3%81vila.jpg","width":800,"height":450,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '040b4a3c-cb7e-53f9-9e02-da4540f52200';

-- Sant Pau Recinte Modernista (en geosearch: Hospital de Sant Pau)
update public.pois
   set photos = '[{"source":"wikimedia","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Hospital_Sant_Pau%2C_main_facade.jpg/960px-Hospital_Sant_Pau%2C_main_facade.jpg","width":800,"height":494,"attribution":"Wikimedia Commons"}]'::jsonb,
       enriched_at = now()
 where id = '0d2475ad-cf89-5186-b6bc-879c7c039bbe';
