-- ============================================================================
-- Cheers — Foursquare enrichment for `public.pois`
-- ----------------------------------------------------------------------------
-- Apply after `20260705170000_place_details_columns.sql`.
--
-- Auto-generated by `scripts/enrich_pois.py`. Regenerate with:
--   python3 scripts/enrich_pois.py > <this file>
--
-- Mode: CORE-ONLY. `rating`/`review_count`/`photos` were NOT
-- populated because the freePro tier returns 429 on Premium fields.
-- Enable billing at https://foursquare.com/developers/orgs and re-run
-- to fill them in — the UPDATEs are keyed on stable UUIDs so they'll
-- overwrite the rows we're writing now.
--
-- Matched: 71 / 72 POIs
-- Misses (1):
--   • Sheoudo Condal — no Foursquare match within 200m
-- ============================================================================

-- Barcelo Raval
update public.pois
   set fsq_id = '4ad35844f964a520e4e320e3',
       enriched_at = now()
 where id = '2ba6c1c1-098f-5a3a-af0b-3470820e7e20';

-- Casa Gràcia
update public.pois
   set fsq_id = '4c2e6903ed37a593bc8b6503',
       enriched_at = now()
 where id = '1f8a3dec-5fda-5e0b-b434-648b1e91f2ae';

-- El Palace Hotel
update public.pois
   set fsq_id = '4daedac5ffcb58f1a90b8249',
       enriched_at = now()
 where id = '5f6d41c1-fed5-5922-9235-1e94df03d1c6';

-- Eurostars Grand Marina
update public.pois
   set fsq_id = '4bc8edfb762beee196b63d38',
       enriched_at = now()
 where id = 'b53090d1-1f5e-5df4-82d7-95de745d0622';

-- H10 Marina Barcelona Hotel
update public.pois
   set fsq_id = '4adcda4cf964a520df3f21e3',
       enriched_at = now()
 where id = '502fe53c-9c91-5e17-8a90-400422761248';

-- Hotel Arts Barcelona
update public.pois
   set fsq_id = '4adcda4cf964a520943f21e3',
       enriched_at = now()
 where id = '6d1dd55c-b637-5ed1-a862-d6499062eee2';

-- Hotel Barceló Sants
update public.pois
   set fsq_id = '4b362632f964a5208b3025e3',
       enriched_at = now()
 where id = 'ac011245-dd5a-5ce7-9c3c-e12c32592ae9';

-- Hotel Casa Fuster
update public.pois
   set fsq_id = '4adcda4df964a520ec3f21e3',
       enriched_at = now()
 where id = '2c8d4dac-05d7-5c57-b157-63f1799e25b9';

-- Hotel Catalonia Barcelona Plaza
update public.pois
   set fsq_id = '4b4d0d25f964a52056c926e3',
       enriched_at = now()
 where id = 'e00a064d-a60e-5290-b9d9-226244018d38';

-- Hotel Condes de Barcelona
update public.pois
   set fsq_id = '4adcda4cf964a5208d3f21e3',
       enriched_at = now()
 where id = '83a5ff20-90fd-5749-bb92-7ca4dbb78f11';

-- Hotel Gargallo Rialto
update public.pois
   set fsq_id = '4d681b6f5b376dcbf6eb7467',
       enriched_at = now()
 where id = '8b6044e8-2080-5080-8fb3-e352093c4690';

-- Intercontinental Barcelona
update public.pois
   set fsq_id = '6210c9ef338bb7084bd66ded',
       enriched_at = now()
 where id = 'b14c098c-06db-5113-b364-47ee87fcdb7b';

-- Majestic Hotel and Spa
update public.pois
   set fsq_id = '4adcda4cf964a520933f21e3',
       enriched_at = now()
 where id = 'b45199f8-d4dc-550b-b0cb-745bc1791c70';

-- Mandarin Oriental Barcelona
update public.pois
   set fsq_id = '522e20cc11d23ade6637be7f',
       enriched_at = now()
 where id = '3daf12a0-55a1-5b1a-adec-21284cc3d806';

-- Meliá Barcelona Sky
update public.pois
   set fsq_id = '4b7b417cf964a520e75a2fe3',
       enriched_at = now()
 where id = '8b5f34c0-fd3d-5565-89f8-25c2ee849049';

-- Novotel Barcelona City
update public.pois
   set fsq_id = '4c6bb97a599fbe9a313d933f',
       enriched_at = now()
 where id = '0cbe66cf-948f-54e3-8989-650381677db9';

-- Sercotel Rosellón
update public.pois
   set fsq_id = '634029933f475b05cd2476c9',
       enriched_at = now()
 where id = '168c49e4-6d56-554f-9fed-6bf53db09b01';

-- W Barcelona
update public.pois
   set fsq_id = '4b3cd7cff964a5201e8825e3',
       enriched_at = now()
 where id = '24634b57-4f50-5359-a2c4-77a4872ea4f9';

-- 7 Portes
update public.pois
   set fsq_id = '4adcda53f964a520804221e3',
       enriched_at = now()
 where id = '752f9ef9-1d7c-52cb-abc6-8fbb1b68c298';

-- Antigua
update public.pois
   set fsq_id = '4bcc216cb6c49c74ed3d9391',
       enriched_at = now()
 where id = '2b41fd08-2f06-56f3-8559-7fa34250b7bd';

-- Arab Halal Marrakech
update public.pois
   set fsq_id = '4d4d54d8d6f3224b3dbc9aa6',
       enriched_at = now()
 where id = 'bc751902-59e2-5a8a-8526-7b1a60ba4530';

-- Asado Bufet Lliure de Carns Argentines
update public.pois
   set fsq_id = '6829e26cc150375e7f9c8a26',
       enriched_at = now()
 where id = '5d71eb41-f11a-57c4-b68d-c46cdcc2d06d';

-- Botafumeiro
update public.pois
   set fsq_id = '4adcda4df964a520f63f21e3',
       enriched_at = now()
 where id = '28f062e3-4290-5592-96fe-c31e1ba27531';

-- Cañete
update public.pois
   set fsq_id = '4c88d9e510523704e797c3f1',
       enriched_at = now()
 where id = 'a80cbebb-942e-52ee-ba69-fb5bc88ba7fe';

-- Ciutat Comtal
update public.pois
   set fsq_id = '4adcda4ef964a5203f4021e3',
       enriched_at = now()
 where id = '1223fc45-8ccc-5f1b-a09c-1dcd12d98e6d';

-- Colom Restaurant
update public.pois
   set fsq_id = '4f19d5ade4b0aa5093213fae',
       enriched_at = now()
 where id = '07a1be0a-8bb4-5fec-bbff-d483dae453db';

-- El Argentino
update public.pois
   set fsq_id = '510bc110e4b075affe7b24bb',
       enriched_at = now()
 where id = '236f89aa-79f0-519c-810e-5e0add527d71';

-- Jesús Restaurant
update public.pois
   set fsq_id = '4c33230766e40f477e75c78b',
       enriched_at = now()
 where id = 'c686ceea-b320-5f77-b0a5-b2c3e4b57a93';

-- La Fonda
update public.pois
   set fsq_id = '628d35973886b51f9d65eb7b',
       enriched_at = now()
 where id = 'bcbd68ca-8e98-5913-8e57-3f31119a725e';

-- Micu Maku
update public.pois
   set fsq_id = '53778673498ef1607a9ae247',
       enriched_at = now()
 where id = '155596f2-4e6a-5ab9-982b-25ae6d0ba173';

-- Mirablau
update public.pois
   set fsq_id = '4adcda4df964a520ff3f21e3',
       enriched_at = now()
 where id = '4336c45f-a487-5779-b745-42b4108531f1';

-- Ocaña
update public.pois
   set fsq_id = '4f6889a5e4b0de0c91aae561',
       enriched_at = now()
 where id = '8a0cc312-2fe9-5d9a-b733-dfc92db89b22';

-- Restaurant La Boqueria
update public.pois
   set fsq_id = '50e45988e4b0f6f2e7380e8d',
       enriched_at = now()
 where id = 'a754ffb7-0b16-56e4-bad0-707766802434';

-- Restaurante La Barca del Salamanca
update public.pois
   set fsq_id = '4adcda53f964a520854221e3',
       enriched_at = now()
 where id = 'dfa5d79b-6cca-5fcc-9279-248a42dec479';

-- Salamanca
update public.pois
   set fsq_id = '4adcda53f964a520854221e3',
       enriched_at = now()
 where id = '20bbfed9-3767-5ee8-9b8a-e681fbdc0ac2';

-- Vivo Tapas
update public.pois
   set fsq_id = '5825bc4b165d973540a22887',
       enriched_at = now()
 where id = 'b4058d2b-ad7a-545a-96fc-e40c0820fbb5';

-- 100 Montaditos
update public.pois
   set fsq_id = '4e4fa313d22daf51d2780497',
       enriched_at = now()
 where id = 'dc651a0c-c129-50bc-b79d-86cd8335222a';

-- Bar del Pla
update public.pois
   set fsq_id = '4b85902af964a520a26531e3',
       enriched_at = now()
 where id = 'c8ede737-edae-5deb-83d4-a5a212e66b36';

-- Bar El Velódromo
update public.pois
   set fsq_id = '4b747bcbf964a5204edf2de3',
       enriched_at = now()
 where id = '24abf157-2c98-5b09-a24f-85f504298f95';

-- Bar Jai-Ca
update public.pois
   set fsq_id = '4b695eb0f964a52035a02be3',
       enriched_at = now()
 where id = '03836d0a-b1be-5199-b5c2-4112d381e02a';

-- Bar Lobo
update public.pois
   set fsq_id = '4adcda4ef964a520954021e3',
       enriched_at = now()
 where id = 'c2d35b47-607f-5bbc-b197-4aad7067ad8f';

-- Bodega Joan
update public.pois
   set fsq_id = '4bdc72cec79cc928469786e9',
       enriched_at = now()
 where id = '3f615976-ee09-5274-ad95-6cc066303c4b';

-- Can Paixano
update public.pois
   set fsq_id = '4b5b708af964a52043fe28e3',
       enriched_at = now()
 where id = '2e07098f-fda7-557a-9b72-7075dc40be2a';

-- Cerveseria Vaso de Oro
update public.pois
   set fsq_id = '4b45d7c0f964a520161126e3',
       enriched_at = now()
 where id = 'a5ceda1c-687b-5eca-b1c9-7cfaa8a70c02';

-- El Bosc de Les Fades
update public.pois
   set fsq_id = '4adcda4ef964a520844021e3',
       enriched_at = now()
 where id = '3618d59c-6a08-54a4-8da8-90e7e5165f49';

-- El Xampanyet
update public.pois
   set fsq_id = '4adcda4ef964a520584021e3',
       enriched_at = now()
 where id = '48aff205-76b2-5a0c-bbaa-859d2476360b';

-- Fàbrica Moritz Barcelona
update public.pois
   set fsq_id = '4ed3c0f002d5feaa201fb8f0',
       enriched_at = now()
 where id = '3b003824-1a3c-51af-b1c5-f181e0811ac0';

-- La Bombeta
update public.pois
   set fsq_id = '4b7a9f07f964a520f4332fe3',
       enriched_at = now()
 where id = '87392bea-d4e2-56f8-b581-e02535a0433e';

-- Michael Collins
update public.pois
   set fsq_id = '4b6c6b4cf964a520a1382ce3',
       enriched_at = now()
 where id = 'c2b6ded1-3a51-5fea-8d19-caf3681fbd86';

-- Paradiso
update public.pois
   set fsq_id = '56904e5d498eb2b8e8fdef64',
       enriched_at = now()
 where id = '42cb4d38-529f-55f9-ac9a-073c16a0668b';

-- Perikete
update public.pois
   set fsq_id = '58a897a319b1ad18d756c142',
       enriched_at = now()
 where id = 'a85d0aff-f5b9-5e1b-99b8-85e4780dc826';

-- Quimet & Quimet
update public.pois
   set fsq_id = '4adcda4df964a520064021e3',
       enriched_at = now()
 where id = '0e773b15-26f0-58cc-9af1-9e65587a5ee8';

-- Tapeo
update public.pois
   set fsq_id = '4c8a3c569ef0224b4edc587b',
       enriched_at = now()
 where id = '3c22db5e-a15b-5b48-b360-685561cd14ea';

-- Arc de Triomf
update public.pois
   set fsq_id = '4adcda50f964a520384121e3',
       enriched_at = now()
 where id = '93db60cb-25df-5dca-8eef-c546a89f2ec5';

-- Barcelona Maritime Museum
update public.pois
   set fsq_id = '4b65aea4f964a52073f92ae3',
       enriched_at = now()
 where id = 'f2117be4-38e2-59b7-b380-c147a6350889';

-- Capella de Santa Agata
update public.pois
   set fsq_id = '4adcda50f964a5206c4121e3',
       enriched_at = now()
 where id = '66c56bf9-56b7-59f8-be3e-a510528d7856';

-- Casa Batlló
update public.pois
   set fsq_id = '4adcda51f964a520aa4121e3',
       enriched_at = now()
 where id = 'ae9f8364-5da0-53a3-b827-dc0f6ac811c0';

-- Casa Vicens Gaudí
update public.pois
   set fsq_id = '4adcda51f964a520ab4121e3',
       enriched_at = now()
 where id = '67f91705-8d09-53ad-b3aa-7d81464da775';

-- CosmoCaixa Museum of Science
update public.pois
   set fsq_id = 'bd8e69c3c8144e38d4ed1d5a',
       enriched_at = now()
 where id = '1cacd6cf-2d61-5aab-9a13-a55212437402';

-- Joan Miró Foundation
update public.pois
   set fsq_id = '4bb79a0a98c7ef3bc90a3002',
       enriched_at = now()
 where id = '25b7d5b8-20c7-5195-81a3-05528b399353';

-- La Pedrera - Casa Milà
update public.pois
   set fsq_id = '4adcda50f964a520354121e3',
       enriched_at = now()
 where id = '8cea3134-5bd8-5402-8670-dcaf64d82ffe';

-- Magic Fountain of Montjuïc
update public.pois
   set fsq_id = '4adcda50f964a520424121e3',
       enriched_at = now()
 where id = 'd5479945-6cb8-5cd7-ab88-334bead53bef';

-- Montjuïc Castle
update public.pois
   set fsq_id = '4adcda50f964a5204b4121e3',
       enriched_at = now()
 where id = '84991060-bbfd-5bde-b4e3-1167b07c4099';

-- Monument a Colom
update public.pois
   set fsq_id = '4b9cfc34f964a5209c8636e3',
       enriched_at = now()
 where id = 'df075847-30e7-52c0-99df-b19540fd7d69';

-- Palau Güell
update public.pois
   set fsq_id = '4adcda50f964a520264121e3',
       enriched_at = now()
 where id = '02f96bbf-a345-527d-a5f9-616b3012ad59';

-- Parc del Mirador del Poble-sec
update public.pois
   set fsq_id = '4e9550ab9a526ce9d8bad3b8',
       enriched_at = now()
 where id = '0a0fe1a7-7f10-533b-a98f-8c0145845750';

-- Park Güell
update public.pois
   set fsq_id = '4b76bca2f964a520975b2ee3',
       enriched_at = now()
 where id = '1aac4ca1-9b7f-5509-a58c-09f95776ea53';

-- Plaça d'Espanya
update public.pois
   set fsq_id = '4b7c12aff964a520517b2fe3',
       enriched_at = now()
 where id = '11c34e22-c882-579e-b0bb-462f6524f865';

-- Plaça de Catalunya
update public.pois
   set fsq_id = '4adcda50f964a520274121e3',
       enriched_at = now()
 where id = '6d7f9975-84db-525b-afd6-aee165e25860';

-- Poble Espanyol
update public.pois
   set fsq_id = '4adcda5af964a520504421e3',
       enriched_at = now()
 where id = '040b4a3c-cb7e-53f9-9e02-da4540f52200';

-- Sant Pau Recinte Modernista
update public.pois
   set fsq_id = '51da77b450194ec38ba7b07e',
       enriched_at = now()
 where id = '0d2475ad-cf89-5186-b6bc-879c7c039bbe';
