-- ============================================================================
-- Cheers — Foursquare enrichment columns on `public.pois`
-- ----------------------------------------------------------------------------
-- Apply after `20260705160000_seed_real_pois.sql`.
--
-- Adds the fields the Flutter client needs to show a hero image + rating
-- chip on each POI detail card. Data is written by
-- `20260705180000_enrich_pois.sql` (regenerated by
-- `scripts/enrich_pois.py`).
--
-- Foursquare's TOS allows caching place data for reasonable durations, so
-- unlike Google Places we can just bake the enrichment straight into the
-- table. The Flutter app never talks to Foursquare at runtime — it just
-- reads these columns and composes photo URLs on the client via
-- `${prefix}${size}${suffix}` (Foursquare's photo-URL convention).
-- ============================================================================


alter table public.pois
  add column if not exists fsq_id       text unique,
  add column if not exists review_count integer not null default 0,
  add column if not exists photos       jsonb   not null default '[]'::jsonb,
  add column if not exists enriched_at  timestamptz;

-- Handy for future maintenance jobs ("which rows haven't been enriched?").
create index if not exists pois_enriched_at_idx
  on public.pois (enriched_at nulls first);
